name: Build and Test

on:
  push:
    branches:
      - '**'

  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++ qtcreator qtbase5-dev qt5-qmake

      - name: Build project
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Debug
          make

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure
