name: Build and Test

on:
  push:
    branches:
      - '**'

  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add repository
        run: sudo add-apt-repository universe multiverse

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake qmake6 g++ qt6-base-dev qt6-tools-dev qt6-tools-static libqt6widgets6 && cmake -DCMAKE_PREFIX_PATH=/usr/lib/qt6 .

      - name: Version qmake
        run: qmake --version

      - name: Build project
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Debug --parallel 4
          make

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure
