name: Build and Test

on:
  push:
    branches:
      - '**'

  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add repository
        run: sudo add-apt-repository universe multiverse

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y qt6-base-dev qt6-tools-dev libqt6widgets6 qt6-base-dev qt6-base-private-dev qt6-declarative-dev qt6-declarative-private-dev qt6-tools-dev qt6-tools-private-dev qt6-scxml-dev qt6-documentation-tools libqt6core5compat6-dev qt6-tools-dev-tools qt6-l10n-tools qt6-shader-baker libqt6shadertools6-dev qt6-quick3d-dev qt6-quick3d-dev-tools libqt6svg6-dev libqt6quicktimeline6-dev libqt6serialport6-dev cmake qmake6 g++

      - name: Version qmake
        run: qmake --version

      - name: Build project
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Debug --parallel 4
          make

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure
