name: Build and Test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up C++ environment
        uses: shivammathur/setup-cpp@v2
        with:
          compiler: gcc

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++ libgtest-dev

      - name: Build tests
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

      - name: Run tests
        run: ./build/test_order
