name: Build and Test

on:
  push:
    branches:
      - '**'

  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add repository
        run: sudo add-apt-repository universe multiverse

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++ libgtest-dev gcc gdb

      - name: Install Qt6
        run: sudo apt-get install -y build-essential libgl1-mesa-dev qt6-base-dev clang qt6-tools-dev qt6-l10n-tools qt6-tools-dev-tools

      - name: Build project
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Debug
          make

      - name: Verify test executables
        run: |
          ls -la build

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure
